# Generated by Django 5.2.3 on 2025-10-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=5)),
                ('image', models.ImageField(upload_to='product')),
                ('release_date', models.TextField()),
                ('lte_exists', models.TextField()),
                ('slug', models.TextField()),
            ],
        ),
    ]
